edition = "2021"
comment_width = 100
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
normalize_doc_attributes = true
style_edition = "2024"
tab_spaces = 2
use_field_init_shorthand = true
wrap_comments = false
